### ISSUE TITLE
Create a login page which redirects to an empty dashboard and a symbol which reflects the user's login

### ISSUE THREAD

**Issue by 0x0elliot** [ArgusOSS/Eye#1]
The API endpoints for authentication are ready. Now, it is time to proceed with putting together a basic frontend that supports auth.

- [ ] Make a login page. 
- [ ] Make it work. It should take care of the state management and protected routes nicely.

**Comment by 0x0elliot** [comment]
Let me know when we can get done with this.

**Comment by 0x0elliot** [comment]
ETA for step 1: tomorrow night
ETA for step 2: We will see.

**Comment by abheektripathy** [comment]
Update:
cloned the admin repo doesn't build on IOS, trying to resolve that.
works on chrome though.

**Comment by 0x0elliot** [comment]
Hold this for the time being. We might shift to react + Typescipt rather than flutter.

**Comment by 0x0elliot** [comment]
We are changing to React-TypeScript from Flutter. Would help our project gather more easy collaborators.
