### ISSUE TITLE
Get the demo to work

### ISSUE THREAD

**Issue by 0x0elliot** [ArgusOSS/Eye#40]
I really want a not-very-functional working dashboard to be there and accessible to the users. For the time being, I have deployed the frontend on vercel. When we are more confident with the backend, we can have it out as well.

- [x] Frontend works neatly

### for Backend to work with the frontend nicely being integrated with it:

- [x] Add a settings variable called "demo_instance" which is a bool. deal with everything considering that if demo_instance == true where demo_instance must be an environment variable then we do not do certain things which are unnecessary post-login.
- [x] Write another docker-compose file for this.
- [x] Shift from Postgres to SQLite from settings.py. Use the same demo_instance variable. 
- [x] ~~Write another entry point, especially for previews which creates a demo user with demo access, but no admin.~~ No need for this anymore
- [x] Disable all other services other than the backend from docker-compose
- [ ] Make it live on https://railway.app/

**Comment by abheektripathy** [comment]
working on this.

**Comment by 0x0elliot** [comment]
ping?

**Comment by 0x0elliot** [comment]
ping?

**Comment by 0x0elliot** [comment]
do one thing, focus on this issue. i am un-assigning you from [this](https://github.com/ArgusOSS/Eye/issues/52)
